// Mock Data for Development

export const mockDashboardStats = {
  total_orchestrations: 156,
  active_orchestrations: 12,
  completed_today: 8,
  total_tasks: 1247,
  success_rate: 94.5,
  average_duration_minutes: 15.3,
  api_keys_count: 5,
  active_agents: 8,
};

export const mockActivityData = [
  { date: 'Mon', orchestrations: 24, tasks: 180 },
  { date: 'Tue', orchestrations: 32, tasks: 240 },
  { date: 'Wed', orchestrations: 28, tasks: 210 },
  { date: 'Thu', orchestrations: 35, tasks: 280 },
  { date: 'Fri', orchestrations: 42, tasks: 320 },
  { date: 'Sat', orchestrations: 18, tasks: 140 },
  { date: 'Sun', orchestrations: 12, tasks: 90 },
];

export const mockRecentOrchestrations = [
  {
    id: '1',
    name: 'Implement user authentication',
    status: 'COMPLETED' as const,
    progress: 100,
    repository_url: 'https://github.com/example/my-app',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    task_count: 5,
    completed_tasks: 5,
  },
  {
    id: '2',
    name: 'Add payment integration',
    status: 'RUNNING' as const,
    progress: 65,
    repository_url: 'https://github.com/example/e-commerce',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    task_count: 8,
    completed_tasks: 5,
  },
  {
    id: '3',
    name: 'Fix database performance',
    status: 'PENDING' as const,
    progress: 0,
    repository_url: 'https://github.com/example/api',
    created_at: new Date(Date.now() - 10800000).toISOString(),
    task_count: 3,
    completed_tasks: 0,
  },
  {
    id: '4',
    name: 'Update documentation',
    status: 'COMPLETED' as const,
    progress: 100,
    repository_url: 'https://github.com/example/docs',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    task_count: 2,
    completed_tasks: 2,
  },
];

export const mockAgents = [
  {
    id: '1',
    name: 'coding-agent',
    display_name: 'Coding Agent',
    category: 'coding' as const,
    status: 'available' as const,
  },
  {
    id: '2',
    name: 'debugging-agent',
    display_name: 'Debugging Agent',
    category: 'debugging' as const,
    status: 'busy' as const,
  },
  {
    id: '3',
    name: 'testing-agent',
    display_name: 'Testing Agent',
    category: 'testing' as const,
    status: 'available' as const,
  },
  {
    id: '4',
    name: 'docs-agent',
    display_name: 'Documentation Agent',
    category: 'documentation' as const,
    status: 'available' as const,
  },
];

export const mockOrchestrations = [
  {
    id: '1',
    name: 'Implement user authentication',
    status: 'COMPLETED' as const,
    progress: 100,
    repository_url: 'https://github.com/example/my-app',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    task_count: 5,
    completed_tasks: 5,
  },
  {
    id: '2',
    name: 'Add payment integration',
    status: 'RUNNING' as const,
    progress: 65,
    repository_url: 'https://github.com/example/e-commerce',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    task_count: 8,
    completed_tasks: 5,
  },
  {
    id: '3',
    name: 'Fix database performance',
    status: 'PENDING' as const,
    progress: 0,
    repository_url: 'https://github.com/example/api',
    created_at: new Date(Date.now() - 10800000).toISOString(),
    task_count: 3,
    completed_tasks: 0,
  },
  {
    id: '4',
    name: 'Update documentation',
    status: 'COMPLETED' as const,
    progress: 100,
    repository_url: 'https://github.com/example/docs',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    task_count: 2,
    completed_tasks: 2,
  },
  {
    id: '5',
    name: 'Refactor legacy code',
    status: 'FAILED' as const,
    progress: 45,
    repository_url: 'https://github.com/example/legacy',
    created_at: new Date(Date.now() - 172800000).toISOString(),
    task_count: 10,
    completed_tasks: 4,
  },
];

export const mockRepositories = [
  {
    id: '1',
    user_id: 'user-1',
    name: 'my-app',
    repository_url: 'https://github.com/example/my-app',
    branch: 'main',
    safety_policy: 'Medium safety level',
    auto_merge: true,
    code_style: 'ESLint + Prettier',
    preferred_agents: ['coding-agent', 'testing-agent'],
    metadata: {},
    created_at: new Date(Date.now() - 2592000000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: 'user-1',
    name: 'e-commerce',
    repository_url: 'https://github.com/example/e-commerce',
    branch: 'develop',
    safety_policy: 'High safety level',
    auto_merge: false,
    code_style: 'Standard JS',
    preferred_agents: ['coding-agent'],
    metadata: {},
    created_at: new Date(Date.now() - 1296000000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const mockTemplates = [
  {
    id: '1',
    user_id: 'user-1',
    name: 'Feature Implementation',
    description: 'Template for implementing new features',
    category: 'Development',
    template_content: 'Implement a new feature that does X',
    variables: [
      { name: 'feature', type: 'string' as const, required: true, description: 'Feature name' },
      { name: 'description', type: 'string' as const, required: true, description: 'Feature description' },
    ],
    is_public: true,
    usage_count: 42,
    created_at: new Date(Date.now() - 2592000000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: 'user-1',
    name: 'Bug Fix',
    description: 'Template for fixing bugs',
    category: 'Bug Fixing',
    template_content: 'Fix the bug where X happens',
    variables: [
      { name: 'bug', type: 'string' as const, required: true, description: 'Bug description' },
      { name: 'steps', type: 'string' as const, required: true, description: 'Steps to reproduce' },
    ],
    is_public: false,
    usage_count: 15,
    created_at: new Date(Date.now() - 1296000000).toISOString(),
    updated_at: new Date(Date.now() - 604800000).toISOString(),
  },
];
